spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/

  datasource:
    url: jdbc:mysql://localhost:3306/murali
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8084


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

order-service:
  messages: 
    ordSuc: Order added successfully
    ordUPda: Order updated successfully
    ordDele: Order deleted successfully
    ordUserFet: Orders fetched successfully
    gettAllOrd: All orders fetched successfully
    ordFiltefet: Filtered orders fetched successfully
