spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/

  datasource:
    url: jdbc:mysql://localhost:3306/murali
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

report-service:
  message: 
    unSuppForm: Unsupported format
    success: success
    fetAllOrders: Fetched all orders
    fetOrdersBySta: Fetched orders by status
    fetOrdersByRan: Fetched orders by date range
    Err: Error generating PDF
