spring:
  application:
    name: UserAccount

  config:
    import: optional:configserver:http://localhost:2222/

logging:
  level:
    org.springframework.cloud.config: DEBUG

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

auth-service:
  messages: 
    userReg: user registration successful
    userFail: user registration failed
    loginSuc: user login successful
    loginErr: invalid credentials
    delMsg: user deleted successful
    delErr: user not found
